### PR TITLE
Added support for using ruby capabilities manually defined as type 'command' because the auto-detected type 'ruby' is not an option for remote agents.

### PR DESCRIPTION
**Pull request by sam2themax**
I believe this PR will address this issue: https://github.com/alienfast/bamboozled-ruby-plugin/issues/5

### CODE REVIEW

**Comment by rosskevin** [comment]
Thanks @sam2themax, looks good. Have you tried with local and remote agents?  Do you know if it works with existing plans or requires reconfiguration?

**Comment by sam2themax** [comment]
@rosskevin I'll work on testing it with a few different configs over the next couple days.  I wanted to submit it early just to get it in front of you.  I'll post screenshots and logs of my testing when complete.

**Comment by rosskevin** [comment]
Ok, let me know when you are good to go, I'll merge/build/test here (local only), then publish.  Thanks again.

**Comment by rosskevin** [comment]
More discussion in #5 to figure out if we go with this pull or consider other attempts.

**Pull request closed without merging**
